status = [
  "Test",
  "Lint"
]

# Maximum duration (in seconds) before timeout
timeout_sec = 3600  # 1 hour, matching your default

# Label configuration from your default
[labels]
approve = ["+approved"]
try = ["+trying"]
try_succeed = ["+tested"]
try_failed = ["+test-failed"]
succeeded=["+succeeded"]
failed=["+failed"]
