name: Multiple Jobs Workflow

on:
  push:
    branches: ["automation/bors/try", "automation/bors/auto"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: |
          echo "Job 1 starting"
          sleep 2
          echo "Job 1 done"
          
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 2
        run: |
          echo "Job 2 starting (depends on job1)"
          sleep 2
          echo "Job 2 done"
          
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Job 3
        run: |
          echo "Job 3 starting (parallel with job1)"
          sleep 5
          echo "Job 3 done"
