name: Simulation Workflow

on:
  push:
    branches: [main, master, "automation/bors/try"]
  pull_request:
    branches: [main, master]

jobs:
  simulate-work:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate work (30s wait)
        run: |
          echo "Simulating intensive work..."
          echo "This will take 30s"
          sleep 30
          echo "Work complete"
