name: Main CI Workflow

on:
    push:
        branches: ["automation/bors/try", "automation/bors/auto"]
    pull_request:
        branches: [main, master]

jobs:
    simulate-work:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Check for [fail] in pushed commits
              if: github.event_name == 'push'
              run: |
                  echo "Checking commit messages in range ${{ github.event.before }}..${{ github.sha }}"
                  if git log --format=%B "${{ github.event.before }}..${{ github.sha }}" | grep -q "\[fail\]"; then
                    echo "Found [fail] in commit message – failing CI"
                    exit 1
                  fi

            - name: Wait
              run: |
                  exit 1
                  sleep 20
