name: Simulation Workflow

on:
  push:
    branches: ["automation/bors/try", "automation/bors/auto"]
  pull_request:
    branches: [main, master]

jobs:
  simulate-work:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check for intentional failure
        run: |
          if git log -1 --pretty=%B | grep -q "\[fail\]"; then
            echo "Found [fail] in commit message - intentionally failing CI"
            exit 1
          fi
          
      - name: Simulate work (20s wait)
        run: |
          echo "Simulating intensive work..."
          echo "This will take 20s"
          sleep 20
          echo "Work complete"
