name: Simulation Workflow

on:
  push:
    branches: ["automation/bors/try", "automation/bors/auto"]

jobs:
  simulate-work:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for [fail] in pushed commits
        if: github.event_name == 'push'
        run: |
          echo "Checking commit messages in range ${{ github.event.before }}..${{ github.sha }}"
          if git log --format=%B "${{ github.event.before }}..${{ github.sha }}" | grep -q "\[fail\]"; then
            echo "Found [fail] in commit message – failing CI"
            exit 1
          fi

      - name: Check for [fail] in PR title
        if: github.event_name == 'pull_request'
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          if echo "${{ github.event.pull_request.title }}" | grep -q "\[fail\]"; then
            echo "Found [fail] in PR title – failing CI"
            exit 1
          fi

      - name: Simulate work (5s wait)
        run: |
          exit 1 
          echo "Simulating intensive work..."
          echo "This will take 5s"
          sleep 5
          echo "Work complete"
          

