name: Dynamic Workflow
on: [push, pull_request]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run test
              run: echo "Running base test" && sleep 5

    foo:
        needs: [test]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run foo
              run: echo "Running foo" && sleep 5

    conclusion:
        needs: [test, foo]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run conclusion
              run: echo "Running conclusion" && sleep 5
